import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { registerTrellisSettings } from '../lib/settings.js'

const settingsPath = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'lib', 'settings.js')

/**
 * Drop comments so the structural assertions below only inspect real code —
 * the module's own docs legitimately name the removed APIs.
 * @param {string} source file text.
 * @returns {string} source with block and line comments removed.
 */
function stripComments(source) {
  return source.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/[^\n]*/g, '')
}

/**
 * Regression guard for the 0.1.7 activation failure:
 * `trellis-workflow: Error: cannot get property "config" without inject`.
 *
 * Cordis 4 guards `ctx.config`, so a getter that read it threw on every call —
 * including the `console.log(... effectiveConfig.get() ...)` at the end of
 * `apply` — which made the whole entry fail to activate.
 */
test('effective config getter never touches the guard-blocked ctx.config', () => {
  const code = stripComments(readFileSync(settingsPath, 'utf8'))
  assert.doesNotMatch(code, /\bctx\.config\b/, 'settings.js must not read ctx.config')
  assert.match(code, /ctx\.fiber/)
})

test('effective config getter reads the live fiber config', () => {
  const ctx = {
    // Exactly what cordis 4 does for an un-injected property.
    get config() {
      throw new Error('cannot get property "config" without inject')
    },
    fiber: { config: { allowlist: ['F:/proj'], injectStep: 4, skipKeywords: ['skip'], inline: true } },
  }
  const effective = registerTrellisSettings(ctx, { allowlist: ['F:/base'], injectStep: 1 })
  const value = effective.get()
  assert.deepEqual(value.allowlist, ['F:/proj'], 'live allowlist wins over the mount-time config')
  assert.equal(value.injectStep, 4)
  assert.deepEqual(value.skipKeywords, ['skip'])
  assert.equal(value.inline, true)
  assert.equal(value.enforceReadonlyPlanning, false, 'schema default fills fields the live config omits')
})

test('effective config getter falls back to the mount-time config', () => {
  // No fiber reachable at all.
  const noFiber = registerTrellisSettings({}, { allowlist: ['F:/base'], injectStep: 2 })
  const a = noFiber.get()
  assert.deepEqual(a.allowlist, ['F:/base'])
  assert.equal(a.injectStep, 2)
  assert.equal(a.inline, false)

  // An undefined entry config must still resolve through the schema defaults.
  const bare = registerTrellisSettings({ fiber: undefined }, undefined)
  const b = bare.get()
  assert.deepEqual(b.allowlist, [])
  assert.equal(b.injectStep, 1)
  assert.deepEqual(b.skipKeywords, ['no-trellis'])
  assert.equal(b.enforceReadonlyPlanning, false)
})

test('a throwing fiber read degrades to the mount-time config instead of propagating', () => {
  const ctx = {
    fiber: {
      get config() {
        throw new Error('boom')
      },
    },
  }
  const effective = registerTrellisSettings(ctx, { allowlist: ['F:/safe'] })
  assert.deepEqual(effective.get().allowlist, ['F:/safe'])
})

/**
 * The 0.1.7 settings page is auto-generated by default
 * (`autoGenerate = presentations.get(fiber)?.auto ?? true`), and opting in from
 * an inject callback fails with "cannot create effect on inactive context".
 * So this module must not call the settings service at all.
 */
test('settings module does not register or configure a namespace', () => {
  const code = stripComments(readFileSync(settingsPath, 'utf8'))
  assert.doesNotMatch(code, /settings\.register/)
  assert.doesNotMatch(code, /settings\.configure/)
})
