/**
 * Settings integration for the trellis trigger (DSH 0.1.7 model).
 *
 * Since 0.1.7 the settings service is Loader-entry driven: each plugin's
 * `Config` schema is projected into a settings form keyed by the loader entry
 * id (`trellis-workflow`), and the Web client reads/writes it through the
 * shared `configForms` service. Plugins no longer register a namespace —
 * `ctx.settings.register()` is gone.
 *
 * Two properties of that model shape this module:
 *
 *  1. The entry's form is generated by default: dsh-settings resolves
 *     `autoGenerate` as `presentations.get(fiber)?.auto ?? true`, so a plugin
 *     does NOT have to opt in. Calling `ctx.settings.configure()` from an
 *     `inject` callback would in fact fail with "cannot create effect on
 *     inactive context", so this module deliberately does not call it.
 *  2. The live effective value must be read from the plugin's own Cordis fiber.
 *     `ctx.config` is guard-blocked ("cannot get property \"config\" without
 *     inject"); `ctx.fiber.config` carries the resolved config the Loader keeps
 *     current as Web-form edits apply. The mount-time argument stays the
 *     fallback, so a composition without a settings provider still works.
 */

import { SCHEMA, unwrapVolatileConfig } from './meta.js'

/**
 * Return a live getter for this plugin's effective config.
 *
 * @param {import('@deepseek-ai/cordis').Context} ctx plugin context.
 * @param {object} config the plugin's entry config (composition `base`).
 * @returns {{ get: () => object }} a live getter for the effective config.
 */
export function registerTrellisSettings(ctx, config) {
  // `apply` receives the config cordis already resolved against `Config`:
  // defaults are applied and every `.volatile()` field arrives as a cosmokit
  // wrapper. So normalize by unwrapping (never by re-validating through the
  // schema, which would resolve the wrappers a second time) and layering it
  // over the schema defaults for anything the entry omitted entirely.
  const defaults = unwrapVolatileConfig(SCHEMA({}))
  const base = { ...defaults }
  for (const [key, value] of Object.entries(unwrapVolatileConfig(config ?? {}))) {
    if (value !== undefined) base[key] = value
  }

  /**
   * Resolve the effective config, preferring the fiber's live resolved config
   * (Web edits land there) and falling back to the mount-time config. Never
   * throws: a throwing getter would fail every tool call and the per-turn
   * breadcrumb with it.
   * @returns {object} plain config values.
   */
  function get() {
    try {
      const live = ctx.fiber && ctx.fiber.config
      if (live !== null && typeof live === 'object') {
        const out = { ...base }
        for (const [key, value] of Object.entries(unwrapVolatileConfig(live))) {
          if (value !== undefined) out[key] = value
        }
        return out
      }
    } catch {
      /* unreachable fiber, or a build whose config is unreadable — use base */
    }
    return base
  }

  return { get }
}
